package WorkoutManagement;

/**
 * Represents a workout class in the gym management system.
 * This class encapsulates all properties of a workout class including
 * ID, type, description, and the assigned trainer.
 */

public class WorkoutClass {

    private String wcId; // WorkoutClass ID
    private String wcType; // WorkoutClass Type
    private String wcDesc; // WorkoutClass Description
    private int trainerId; //Trainer ID

    /**
     * Constructs a new WorkoutClass with all specified parameters.
     * 
     * @param wcId the unique identifier for the workout class
     * @param wcType the type of workout (Cardio, Strength, Yoga, etc.)
     * @param wcDesc a description of the workout class content
     * @param trainerId the ID of the trainer assigned to this class
     */

    public WorkoutClass(String wcId, String wcType, String wcDesc, int trainerId) {
        this.wcId = wcId;
        this.wcType = wcType;
        this.wcDesc = wcDesc;
        this.trainerId = trainerId;
    }

    /**
     * Constructs a new WorkoutClass without specifying the ID.
     * The ID is typically auto-generated by the database.
     * 
     * @param wcType the type of workout (Cardio, Strength, Yoga, etc.)
     * @param wcDesc a description of the workout class content
     * @param trainerId the ID of the trainer assigned to this class
     */

    public WorkoutClass(String wcType, String wcDesc, String trainerId) {
        this.wcType = wcType;
        this.wcDesc = wcDesc;
    }

    /**
     * Default constructor for creating an empty WorkoutClass object.
     */

    public WorkoutClass() {
    }

    /**
     * Gets the workout class ID.
     * 
     * @return the unique identifier for this workout class
     */

    public String getWcId() {
        return wcId;
    }

    /**
     * Sets the workout class ID.
     * 
     * @param wcId the unique identifier to set for this workout class
     */

    public void setWcId(String wcId) {
        this.wcId = wcId;
    }

    /**
     * Gets the workout class type.
     * 
     * @return the type of workout (Cardio, Strength, Yoga, etc.)
     */

    public String getWcType() {
        return wcType;
    }

    /**
     * Sets the workout class type.
     * 
     * @param wcType the type of workout to set
     */

    public void setWcType(String wcType) {
        this.wcType = wcType;
    }

    /**
     * Gets the workout class description.
     * 
     * @return the description of the workout class content
     */

    public String getWcDesc() {
        return wcDesc;
    }

    /**
     * Sets the workout class description.
     * 
     * @param wcDesc the description of the workout class content to set
     */

    public void setWcDesc(String wcDesc) {
        this.wcDesc = wcDesc;
    }

    /**
     * Gets the trainer ID assigned to this workout class.
     * 
     * @return the ID of the trainer responsible for this class
     */

    public String getTrainerId() {
        return trainerId;
    }

    /**
     * Sets the trainer ID for this workout class.
     * 
     * @param trainerId the ID of the trainer to assign to this class
     */

    public void setTrainerId(String trainerId) {
        this.trainerId = trainerId;
    }

}
