package MembershipManagement;

/**
 * Represents a gym membership in the membership management system.
 * This class encapsulates all properties of a membership including
 * ID, type, description, cost, and associated user.
 */

public class Membership {

    private String msId;
    private String msType;
    private String msDesc;
    private double msCost;
    private int userId;

    /**
     * Constructs a new Membership with specified parameters.
     * The membership ID is typically auto-generated by the database.
     * 
     * @param msType the type of membership (Basic, Premium, VIP, etc.)
     * @param msDesc a description of the membership benefits
     * @param msCost the cost of the membership in dollars
     * @param userId the ID of the user purchasing this membership
     */

    public Membership(String msType, String msDesc, double msCost, int userId) {
        this.msType = msType;
        this.msDesc = msDesc;
        this.msCost = msCost;
        this.userId = userId;
    }

    /**
     * Default constructor for creating an empty Membership object.
     */

    public Membership() {
    }

    /**
     * Gets the membership ID.
     * 
     * @return the unique identifier for this membership
     */

    public String getMsId() {
        return msId;
    }

    /**
     * Sets the membership ID.
     * 
     * @param msId the unique identifier to set for this membership
     */

    public void setMsId(String msId) {
        this.msId = msId;
    }

    /**
     * Gets the membership type.
     * 
     * @return the type of membership (Basic, Premium, VIP, etc.)
     */

    public String getMsType() {
        return msType;
    }

    /**
     * Sets the membership type.
     * 
     * @param msType the type of membership to set
     */

    public void setMsType(String msType) {
        this.msType = msType;
    }

    /**
     * Gets the membership description.
     * 
     * @return the description of membership benefits and features
     */

    public String getMsDesc() {
        return msDesc;
    }

    /**
     * Sets the membership description.
     * 
     * @param msDesc the description of membership benefits to set
     */

    public void setMsDesc(String msDesc) {
        this.msDesc = msDesc;
    }

    /**
     * Gets the membership cost.
     * 
     * @return the cost of the membership in dollars
     */

    public double getMsCost() {
        return msCost;
    }

    /**
     * Sets the membership cost.
     * 
     * @param msCost the cost of the membership in dollars
     */

    public void setMsCost(double msCost) {
        this.msCost = msCost;
    }

    /**
     * Gets the user ID associated with this membership.
     * 
     * @return the ID of the user who owns this membership
     */

    public int getUserId() {
        return userId;
    }

    /**
     * Sets the user ID for this membership.
     * 
     * @param userId the ID of the user to associate with this membership
     */
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
}
